# -*- coding: utf-8 -*-
"""Code for entire_Deep learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1azdq2AvzfXbmHyeAqylRzmkz1ggSNqqQ

<h1><center><b><font size='10'>[Code for Neuralearn Courses]</font></b></center></h1>

 Congratulations 🎉🎉🎉 for getting here.
 You are indeed determined to Master AI by implementing all the projects in this notebook!
 <br>
 Join more than <b>15000 learners</b> today by saving 💲<b>300</b> and access All our Premium Courses at <b>💲24.5</b> instead of <s>💲<b>99</b></s>  

https://neuralearn.podia.com/?coupon=MASTERY_OF_AI

<br>
 Contact us at: team@neuralearn.ai for any enquiries

#Deep Learning for Computer Vision

<b>You can now access all the code for the Course <font color ="orange">Deep Learning for Computer Vision</font>  [Go to Course](https://www.neuralearn.ai/course/computer_vision/)

<i>Linear Regression for Predicting the Price of Second Hand Cars:</i> <br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20computer%20vision/1-Linear%20Regression%20for%20Predicting%20Price%20of%20second%20hand%20Cars%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1_06FCpGN90Gy01mwZMqcepXzJsKDLWs6) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Malaria Detection:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20computer%20vision/2-Malaria%20Detection%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1tqRYQac8AwOkVWnKK8Vr0cJX7Rn7Z_tZ) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Malaria Detection [Pytorch Version]:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20computer%20vision/3-Malaria%20Detection%20by%20Neuralearn.ai%20%5BPyTorch%20Version%5D-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1876kWPsUPSnuu9WxKLv7Uf1WprJqjRGU) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Human Emotions Detection:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20computer%20vision/4-Human%20Emotions%20Detection%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1WKIdwZY5Muqx5xFIsc9jDQ2R_vVK7-AY) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Object detection from scratch with YOLO:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20computer%20vision/5-YOLO%20Object%20Detection%20from%20Scratch%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/15fAyGUpK931O5hIRXCRz1LO6qUOqenlg) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Image segmentation with a UNET Mode:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20computer%20vision/6-Image%20segmentation%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1oO4vaxRiAk2xbtqMHdwpPzavq7yLAX0v) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>People Counting with CSRNET Model:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20computer%20vision/7-People%20Counting%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1txaGPZCPgDhoX3tTwU0PHul20TMPdjfJ) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Digits Generation with Variational Autoencoders:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20computer%20vision/8-VAE%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/16Ul8UW2yccQB5JVoCnGmt_xj3d633zxQ) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Face Generation with DCGANs:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20computer%20vision/9-DCGAN%20By%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1kPxkY-sQPMj8TPL3oj4nseuA40lKEiMM) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

#Deep Learning for Natural Language Processing

<b>You can now access all the code for the Course <font color ="orange">Deep Learning for Natural Language Processing</font>  [Go to Course](https://www.neuralearn.ai/course/natural_language_processing/)

<i>Linear Regression for Predicting the Price of Second Hand Cars:</i> <br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20natural%20language%20processing/1-Linear%20Regression%20for%20Predicting%20Price%20of%20second%20hand%20Cars%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1_06FCpGN90Gy01mwZMqcepXzJsKDLWs6) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Sentiment Analysis with Recurrent Neural Networks:</i> <br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20natural%20language%20processing/2-Sentiment%20Analysis%20with%20RNNs%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1heR_QTL_JEa2fCnzXumbbwMbduB7Saa_) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Sentiment Analysis with Transformers:</i> <br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20natural%20language%20processing/3-Sentiment%20Analysis%20with%20Transformers%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/18fwZzttOw5y6evn1EKLfF45wPTSJPBrv) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Neural Machine Translation with Recurrent Neural Networks:</i> <br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20natural%20language%20processing/4-Neural%20Machine%20Translation%20with%20RNNs%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1XWMrg8yb-y4rqKjp1wIZ8G1nl_C_-rwy) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Neural Machine Translation with Bahdanau Attention:</i> <br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20natural%20language%20processing/5-Neural%20Machine%20Translation%20with%20Bahdanau%20Attention%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1cgH2ujsmgDQ-UABJ1FQg-Yo9LXKW5yHB)

<i>Neural Machine Translation with Transformers:</i> <br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20natural%20language%20processing/6-Neural%20Machine%20Translation%20with%20Transformers%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1FACGCwIcoCGPIfsAM0qBDAnm6ZsusWMM) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Sentiment Analysis with Bert using Huggingface Transformers:</i> <br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2)<br>
[Run on Colab](https://colab.research.google.com/drive/1NSptGzjbgxXIhwIAbtiTCcXuGvG5YhPE) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Intent Classification with Deberta using Huggingface Transformers:</i> <br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2)<br>
[Run on Colab](https://colab.research.google.com/drive/110v8mbJSsMzmKS1FIAliAacdGCKm5b9w) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Named Entity Recognition with Roberta using Huggingface Transformers:</i> <br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20natural%20language%20processing/7-Sentiment%20Analysis%20with%20BERT%20in%20HuggingFace%20%F0%9F%A4%97%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1xISX3HE2FtC0PS-kVWcJozXkD8qB8fCF)

<i>Neural Machine Translation with T5 using Huggingface Transformers:</i> <br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20natural%20language%20processing/10-Neural%20Machine%20Translation%20using%20HuggingFace%20%F0%9F%A4%97%20Transformers%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/108-1eRiKsNcrpP7v-ThwS3rB2v0E6Yw5) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Extractive Question Answering with Longformer using Huggingface Transformers:</i> <br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20natural%20language%20processing/11-Extractive%20Question%20Answering%20using%20HuggingFace%20%F0%9F%A4%97%20Transformers%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/13v_mn9rTw1cvW-sjGqin8QpkItGrlshV) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Ecommerce Search Engine with Sentence Transformers using Huggingface Transformers:</i> <br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20natural%20language%20processing/12-Search%20Engine%20for%20e-commerce%20using%20Sentence%20Transformers%20in%20HuggingFace%20%F0%9F%A4%97%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1VauOYf7BxjdT9ETTv5CaPTOl1i9xd-V2) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Drake Lyrics Generator with GPT2 using Huggingface Transformers:</i> <br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20natural%20language%20processing/13-Lyrics%20Generator%20using%20GPT2%20in%20HuggingFace%20%F0%9F%A4%97%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1ZZ3MIwIib0crysLg7HYwiP73u7F675T4) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Grammatical Error Correction with T5 using Huggingface Transformers:</i> <br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20natural%20language%20processing/14-Grammatical%20Error%20Correction%20using%20T5%20in%20HuggingFace%20%F0%9F%A4%97%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1Xd3_xXPjUK_UA12IN3AjM9u4EFnv8deU) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Chat With Elon Musk with Blenderbot using Huggingface Transformers:</i> <br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20natural%20language%20processing/15-Chat%20With%20Elon%20Musk%20using%20BlenderBot%20in%20HuggingFace%20%F0%9F%A4%97%20Transformers%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/16DmOKrKNUOWRMYF-YPQWdRPbn8CLfulJ) (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

#Deep Learning for Image Generation with GANs and Diffusion Models

<b>You can now access all the code for the Course <font color ="orange">Deep Learning for Image Generation with GANs and Diffusion Models</font>  [Go to Course](https://neuralearn.ai/course/image_generation)

<i>Digits Generation with Variational Autoencoders:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20image%20generation/1-VAE%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/16Ul8UW2yccQB5JVoCnGmt_xj3d633zxQ)  (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Face Generation with DCGANs:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20image%20generation/2-DCGAN%20By%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1kPxkY-sQPMj8TPL3oj4nseuA40lKEiMM)

<i>Stable GAN Training with WGANs:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20image%20generation/3-WGAN%20By%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1V_pSSMlAErgPtBl3LmCdi4UbQUOj4DRC)  (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>High quality Face Generation with ProGANs:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20image%20generation/4-ProGAN%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1mBL5d--doJ4ZKkM_kOzSn_n1-o0pr3rg)  (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Image Super resolution with SRGANs:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20image%20generation/5-SRGAN%20By%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1tCxn4FaD6aUAdlfJjs32AoltUHxrfYm0)

<i>Face Mask removal with Cyclegans:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20image%20generation/6-CycleGAN%20By%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1hirfdCJlf1y3XMI7zWio5rbUnmDL7LG3)  (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

<i>Face Generation with Diffusion Models:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20image%20generation/7-Diffusion%20Models%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1FMiIc8u8gSdV7TdM62JIBaFqR73GaRXK?usp=share_link)

#Deep Learning for Object Detection

<b>You can now access all the code for the Course <font color ="orange">Deep Learning for Object Detection</font>  [Go to Course](https://www.neuralearn.ai/course/object_detection/)

<i>Testing and Training YOLOX with Custom Data:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20object%20detection/Deploying%20YoloX%20to%20Cloud%20by%20Neuralearn-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1wqwaDtDy86xAeSCzemh5CiEbkkRSPdxW)  (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

#Deep Learning for Optical Character Recognition (OCR)

<b>You can now access all the code for the Course <font color ="orange">Deep Learning for Optical Character Recognition (OCR)</font>  [Coming Soon...]

<i>Converting PDF tables to Excel Sheet:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20optical%20character%20recognition/PDF%20TO%20EXCEL%20By%20Neuralearn-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1nb7veBv2L99z80U0c4gp0fezx-t6DdIp)  (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

#Beginner to Expert Linear Algebra

<b>You can now access all the code for the Course <font color ="orange">Deep Learning for Beginner to Expert Linear Algebra</font>

<i>Converting PDF tables to Excel Sheet:</i><br>
[Get Code on Github](https://github.com/Neuralearn/deep-learning-with-tensorflow-2/blob/main/deep%20learning%20for%20linear%20algebra/Complete%20Linear%20Algebra%20Course%20by%20Neuralearn.ai-.ipynb)<br>
[Run on Colab](https://colab.research.google.com/drive/1ZMGbswclOVxGQX1E1o1kLW51wC0GkSXx)  (Please Check your <b>mail inbox or spam</b> in <b>5 minutes</b> to access the code)

# .

.

.

.

.

.

.

.

# .

<center><img src="http://i.countdownmail.com/24h32u.gif" border="0" alt="countdownmail.com"/></center>
"""